import 'package:flutter/material.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';

class AppTheme {
  static const ColorScheme lightScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff2e59b8),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffdae2ff),
    onPrimaryContainer: Color(0xff001848),
    secondary: Color(0xff585e71),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffdce2f9),
    onSecondaryContainer: Color(0xff151b2c),
    tertiary: Color(0xff735471),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xfffed7f9),
    onTertiaryContainer: Color(0xff2b122b),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    background: Color(0xfff8f6fd),
    onBackground: Color(0xff1b1b1f),
    surface: Color(0xfff8f6fd),
    onSurface: Color(0xff1b1b1f),
    surfaceVariant: Color(0xffdcdeea),
    onSurfaceVariant: Color(0xff45464f),
    outline: Color(0xff757780),
    outlineVariant: Color(0xffc5c6d0),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2f3137),
    onInverseSurface: Color(0xfff2f0f4),
    inversePrimary: Color(0xffb2c5ff),
    surfaceTint: Color(0xff2e59b8),
  );

  static ThemeData get lightTheme => FlexThemeData.light(
    colors: const FlexSchemeColor(
      primary: Color(0xff1145a4),
      primaryContainer: Color(0xffacc7f6),
      secondary: Color(0xffb61d1d),
      secondaryContainer: Color(0xffec9f9f),
      tertiary: Color(0xff376bca),
      tertiaryContainer: Color(0xffcfdbf2),
      appBarColor: Color(0xffcfdbf2),
      error: Color(0xffb00020),
    ),
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
    blendLevel: 7,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 10,
      blendOnColors: false,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      alignedDropdown: true,
      useInputDecoratorThemeInDialogs: true,
      inputDecoratorRadius: 8,
      inputDecoratorBorderWidth: 1,
      inputDecoratorFocusedBorderWidth: 2,
      textButtonRadius: 8,
      elevatedButtonRadius: 8,
      outlinedButtonRadius: 8,
    ),
    keyColors: const FlexKeyColors(),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
  );
} 